apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  # Number of desired pod replicas
  selector:
    matchLabels:
      app: nginx  # The label used to select the pods
  template:
    metadata:
      labels:
        app: nginx  # Label applied to the pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.6  # Nginx container image
        ports:
        - containerPort: 80  # Port exposed on the pod
