apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Matches pods with this label
  ports:
    - protocol: TCP
      port: 80  # Service port (external)
      targetPort: 80  # Port on the pod (container port)
  type: LoadBalancer  # Change to NodePort if you're running locally
