# Default values for nginx-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3  # Increased replicas for load handling

image:
  repository: nginx  # Use the official Nginx image
  pullPolicy: IfNotPresent
  tag: "latest"  # Specify the tag for the Nginx image

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: true  # Enable ingress
  className: ""
  annotations: {}
  hosts:
    - host: nginx-web.local  # Change host as necessary
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
