apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default  # Specify the namespace
subjects:
- kind: User  # This can be 'User', 'Group', or 'ServiceAccount'
  name: your-username  # Replace this with the actual username or service account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader  # This refers to the 'pod-reader' role
  apiGroup: rbac.authorization.k8s.io
