replicaCount: 2

image:
  repository: nginx
  tag: latest

service:
  type: LoadBalancer  # Change to LoadBalancer
  port: 80

ingress:
  enabled: false
  hosts:
    - host: nginx.local
      paths:
        - /
