# storage-class.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: kubernetes.io/aws-ebs   # Specify the provisioner (e.g., AWS EBS)
parameters:
  type: gp2                          # EBS volume type
  fsType: ext4                       # File system type
reclaimPolicy: Retain

