apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Matches pods with this label
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 80  # Port on the pod (containerPort)
  type: LoadBalancer  # Use NodePort if you're not in a cloud environment
