apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Matches the ReplicaSet pods
  ports:
    - protocol: TCP
      port: 80  # Expose port 80
      targetPort: 80  # Target the container's port
  type: LoadBalancer  # Use NodePort for non-cloud setups
