apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  type: LoadBalancer  # Change to LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: nginx
